version: '3'

services:
  mongo:
    image: mongo:4.0-rc
    container_name: user-pool-db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ${MONGO_DATA_PATH:-./.data}:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017