export enum Events {
  ERROR = 'ERROR',
  MASTER_AUTHENTICATED = 'MASTER_AUTHENTICATED',
  CONSUMER_CREATED = 'CONSUMER_CREATED',
  CONSUMER_AUTHENTICATED = 'CONSUMER_AUTHENTICATED',
  CONSUMER_AUTHENTICATION_FAILED = 'CONSUMER_AUTHENTICATION_FAILED',
  GROUP_REGISTERED = 'GROUP_REGISTERED',
  GROUP_REGISTRATION_FAILED = 'GROUP_REGISTRATION_FAILED',
  POLICY_REGISTERED = 'POLICY_REGISTERED',
  POLICY_REGISTRATION_FAILED = 'POLICY_REGISTRATION_FAILED'
}