export enum Events {
  ERROR = 'ERROR',
  MASTER_AUTHENTICATED = 'MASTER_AUTHENTICATED',
  CONSUMER_CREATED = 'CONSUMER_CREATED',
  CONSUMER_AUTHENTICATED = 'CONSUMER_AUTHENTICATED',
  CONSUMER_AUTHENTICATION_FAILED = 'CONSUMER_AUTHENTICATION_FAILED'
}